name: Deploy to StakeReloadXS.com
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd /backend
          npm install package
      - name: Build and deploy
        run: |
          npm run build
          gh pages publish --delete-all
